# .jolt9 in a directory will be treated as a cache and configuration directory.
vaults:
  ha: "sops:./ha.secrets.env"
  shared: 
    uri: "sops:./shared.secrets.env"
    shared: true
    with:
      name: shared
  other:
    url: "azurekv://vaultname?mi=true"

envs:
  ha: # assumes ./ha.env
  default: # assumes "default" for env, vaults, but for server assumes localhost, 

  other:
    vars: 
      OTHER: v 
    imports:
      - "./shared.env"
      - "./other.env"

traefik:
  default:
    acme:
      email: ${{ secrets.ACME_EMAIL }}
    static: 
      entrypoints:
        https:
          address: ":443"
        http:
          address: ":80"
        test:
          - vars="test"

servers:
  sshConfig: true

dns:
  cloudflare: "cloudflare:?CF_API_TOKEN=${CF_API_TOKEN}?ACME=true"
  default: hostfile

contexts:
  ha: # assumes env, vaults, and server use 'ha' as the name
    sshConfig: "./ha.ssh_config"
    dns: cloudflare

projects:
  include:
    - "src"
