# file for giving 
id: "@org/globally-unique-id"
version: 1.0.0

# shared tasks
jobs:
  before_deploy:
    - run: |
        echo "before deploy"
      shell:

contexts:
  default: 
    app: 
      proxy:
        domain: "example.com"
        port: 80
      traefik:
        ignore: true # handled by the compose file
        middleware: 
          - name: "redirect"
            type: "redirect"
            params: 
              regex: "^https://(.*)"
              replacement: "https://www.$${1}"
              permanent: true
      compose: 
        extends: 
          file: "./compose.yaml"
          service: "traefik"



  ha:
    compose: 
      service: 
        traefik:
          extends: 
            file: "./compose.yaml"
            service: "traefik"

      

    # restrict the envs to use
    envs: 
      use: "./ha.env"

    # only use the secrets
    secrets:
      - name: PG_PASSWORD  # if key is not provided, it will be the same as name
        gen: true # generate if not exists
        # vault is not provided, it will assume the default vault


    traefik:
      exclude: true # probably already handled by the compose file
      rules:
        - host: "ha.example.com"
          entrypoints: ["https"]

    zone: |
      mayap 

    jobs:
      before_deploy:
        - run: |
            echo "before deploy"
          shell:
      
