# file for giving 
id: "@org/globally-unique-id"
version: 1.0.0

# shared tasks
jobs:
  before_deploy:
    - run: |
        echo "before deploy"
      shell:

contexts:
  ha:
    compose: ./ha.compose.yaml

    # restrict the envs to use
    envs: 
      include: [ha]
      vars: [PG_PASSWORD]

    # only use the secrets
    secrets:
      - name: PG_PASSWORD  # if key is not provided, it will be the same as name
        gen: true # generate if not exists
        # vault is not provided, it will assume the default vault

    traefik:
      exclude: true # probably already handled by the compose file

    zone: |
      mayap 

    jobs:
      before_deploy:
        - run: |
            echo "before deploy"
          shell:
      
